services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: thunder_market_db
        MYSQL_USER: user
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
